apiVersion: v1
kind: Pod

metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
  - name: client
    image: complex-client
    imagePullPolicy: Never
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 3000
